#!/usr/bin/env python3
"""Build a customer-facing PSKA walkthrough from recorded WebUI clips.

The source recordings are generated by ``record_hermes_pska_extension_demo.cjs``.
This script only trims and concatenates real browser recordings. It does not
create slides, synthetic UI, or narration audio.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEMO_DIR = ROOT / "demo" / "browser" / "hermes_pska_extension_demo"
DIST_DIR = DEMO_DIR / "dist"
DEFAULT_OUTPUT_BASENAME = "hermes_pska_customer_walkthrough_demo"
SIDEBAR_HISTORY_MASK_FILTER = "drawbox=x=48:y=80:w=300:h=580:color=0b0d19@1:t=fill"
SIDEBAR_HISTORY_LOWER_EDGE_MASK_FILTER = "drawbox=x=48:y=640:w=64:h=80:color=0b0d19@1:t=fill"


@dataclass(frozen=True)
class Clip:
    id: str
    title: str
    source: str
    start: float
    end: float
    caption: str
    narration: str | None = None
    hide_sidebar: bool = False

    @property
    def duration(self) -> float:
        return self.end - self.start


CLIPS = [
    Clip(
        id="entry",
        title="对话工作台入口",
        source="hermes_pska_extension_demo_long.mp4",
        start=0.0,
        end=11.730,
        caption="先从日常对话工作台进入，用户不用切换到另一个复杂系统。",
        narration=(
            "我们先从用户每天使用的对话工作台开始。用户不用再打开一个新的系统，也不用先学习一套复杂界面。"
            "知识助手就放在原来的聊天入口旁边，用户照常提问，资料、记忆和后续动作都在这个工作流里完成。"
        ),
        hide_sidebar=True,
    ),
    Clip(
        id="connection",
        title="连接状态",
        source="hermes_pska_extension_demo_long.mp4",
        start=11.730,
        end=31.038,
        caption="旁边的小入口只负责操作，真正的资料整理和记忆管理在后台完成。",
        narration=(
            "这里可以看到知识助手已经连接。这个小入口只是操作面板，真正的工作在后台完成："
            "它会读取用户允许的资料，整理本轮问题需要的内容，并把可以长期保存的内容交给用户确认。"
            "所以它不是另起一个平台，而是给现有对话工作台补上资料和记忆能力。"
        ),
    ),
    Clip(
        id="scope",
        title="本轮资料范围",
        source="hermes_pska_extension_demo_long.mp4",
        start=31.038,
        end=41.808,
        caption="每次提问前，用户可以指定这轮只看哪些资料，系统不会乱扫全盘。",
        narration=(
            "接下来选择本轮资料范围。用户可以指定这次只看某个文件夹、某个项目资料，或者某一类材料。"
            "这样做的好处很直白：不需要把所有个人文件都交出去，也不会让无关资料干扰回答。"
        ),
    ),
    Clip(
        id="overview",
        title="开始前总览",
        source="hermes_pska_extension_demo_long.mp4",
        start=41.808,
        end=63.505,
        caption="开始前先看一眼：有哪些资料、哪些记忆待确认、下一步该做什么。",
        narration=(
            "开始前总览相当于一次开工检查。它会告诉用户，现在有哪些资料可以用，"
            "有哪些内容还在等待确认，接下来适合先查什么、先问什么。"
            "用户不用自己翻文件夹，也不用记住每个资料放在哪里。"
        ),
    ),
    Clip(
        id="pre_answer_context",
        title="回答前整理",
        source="hermes_pska_extension_demo_long.mp4",
        start=63.505,
        end=106.317,
        caption="回答前，系统把相关资料、已有记忆、操作记录和建议整理给助手。",
        narration=(
            "回答前整理是整套流程的关键。系统会先把相关资料找出来，再加上已经确认过的已有记忆、"
            "最近的操作记录和下一步建议，整理成一份干净的参考材料。"
            "助手回答时不是凭空猜，而是先看到这些来源清楚的内容。"
        ),
    ),
    Clip(
        id="chat_memory_tasks",
        title="对话、记忆和任务",
        source="hermes_pska_extension_demo_long.mp4",
        start=106.317,
        end=180.206,
        caption="用户仍然在对话框里发问；回答之后，可以查看记录、确认记忆、同步任务。",
        narration=(
            "现在用户照常在对话框里提问。回答完成后，用户可以继续查看这次用了哪些资料，"
            "哪些内容适合确认记忆，哪些事情需要同步任务。"
            "这里最重要的是控制权：长期记忆不会悄悄写入，必须经过用户确认。"
        ),
        hide_sidebar=True,
    ),
    Clip(
        id="finance_evidence",
        title="财报资料找回",
        source="hermes_pska_finance_case_demo.mp4",
        start=20.127,
        end=51.000,
        caption="在财报场景里，它会从授权文件夹找出收入、毛利、现金流和库存等材料。",
        narration=(
            "第一个实际场景是财报调研。用户把二零二六年第二季度的材料放进授权文件夹后，"
            "知识助手会找出收入、毛利、现金流、库存、回款和未交付订单这些关键信息。"
            "分析人员不需要一页页翻材料，可以先得到一份有依据的资料清单。"
        ),
        hide_sidebar=True,
    ),
    Clip(
        id="finance_report",
        title="经营报告草稿",
        source="hermes_pska_finance_case_demo.mp4",
        start=51.000,
        end=101.670,
        caption="助手再把资料整理成事实、推断和建议，方便形成经营报告草稿。",
        narration=(
            "接着，助手把这些材料整理成经营报告草稿。它会尽量区分三类内容："
            "资料里已经写明的事实、根据事实得到的判断，以及后续可以跟进的建议。"
            "这样客户拿到的不是一段泛泛而谈的总结，而是可以继续审阅和修改的工作稿。"
        ),
        hide_sidebar=True,
    ),
    Clip(
        id="webnovel_answer",
        title="小说续写准备",
        source="hermes_pska_webnovel_case_demo.mp4",
        start=49.355,
        end=89.216,
        caption="在创作场景里，它会找回设定、读者反馈和章节问题，帮助续写前恢复上下文。",
        narration=(
            "第二个实际场景是长篇创作。作者在续写前，最痛苦的往往不是没有灵感，"
            "而是忘了前文设定、角色限制和读者反馈。这里知识助手会把设定资料、章节问题和反馈一起找回，"
            "帮助作者先恢复上下文，再开始写。"
        ),
        hide_sidebar=True,
    ),
    Clip(
        id="eidolia_canvas",
        title="创作画布",
        source="hermes_pska_webnovel_case_demo.mp4",
        start=109.072,
        end=132.633,
        caption="最后，创作画布把想法和产物连起来，资料可以变成可审阅的续写草稿。",
        narration=(
            "最后进入创作画布。画布里只保留两类东西：想法和产物。"
            "设定、反馈和资料可以成为想法节点，续写草稿、报告草稿和可交付内容就是产物节点。"
            "这样用户不是只得到一次回答，而是把资料、思路和成果留在一个可以继续推进的空间里。"
        ),
        hide_sidebar=True,
    ),
]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--demo-dir", type=Path, default=DEMO_DIR)
    parser.add_argument("--output-basename", default=DEFAULT_OUTPUT_BASENAME)
    parser.add_argument("--keep-build", action="store_true")
    args = parser.parse_args()

    demo_dir = args.demo_dir.resolve()
    dist_dir = demo_dir / "dist"
    build_dir = dist_dir / f"{args.output_basename}_build"
    build_dir.mkdir(parents=True, exist_ok=True)

    validate_sources(dist_dir)
    timeline = render_clips(dist_dir, build_dir)

    output_mp4 = dist_dir / f"{args.output_basename}.mp4"
    output_srt = dist_dir / f"{args.output_basename}.zh.srt"
    output_storyboard = dist_dir / f"{args.output_basename}_storyboard.zh.md"
    output_voiceover = dist_dir / f"{args.output_basename}_voiceover.zh.md"
    output_manifest = dist_dir / f"{args.output_basename}_manifest.json"

    concat_clips(build_dir, output_mp4)
    write_srt(timeline, output_srt)
    write_storyboard(timeline, output_storyboard)
    write_voiceover(timeline, output_voiceover)
    write_manifest(
        args.output_basename,
        timeline,
        output_mp4,
        output_srt,
        output_storyboard,
        output_voiceover,
        output_manifest,
    )

    if not args.keep_build:
        shutil.rmtree(build_dir, ignore_errors=True)

    print(f"video: {output_mp4}")
    print(f"subtitles: {output_srt}")
    print(f"storyboard: {output_storyboard}")
    print(f"voiceover: {output_voiceover}")
    print(f"manifest: {output_manifest}")
    return 0


def validate_sources(dist_dir: Path) -> None:
    missing = [dist_dir / clip.source for clip in CLIPS if not (dist_dir / clip.source).exists()]
    if missing:
        raise SystemExit(
            "missing source recording(s):\n"
            + "\n".join(str(path) for path in missing)
            + "\nRun scripts/record_hermes_pska_extension_demo.cjs for the core, finance, and webnovel cases first."
        )
    for clip in CLIPS:
        duration = ffprobe_duration(dist_dir / clip.source)
        if clip.end > duration + 0.1:
            raise SystemExit(f"{clip.source} is too short for clip {clip.id}: {duration:.3f}s < {clip.end:.3f}s")


def render_clips(dist_dir: Path, build_dir: Path) -> list[dict[str, Any]]:
    timeline = []
    cursor = 0.0
    segment_paths = []
    for index, clip in enumerate(CLIPS, start=1):
        output = build_dir / f"{index:02d}_{clip.id}.mp4"
        render_clip(dist_dir / clip.source, output, clip)
        segment_paths.append(output)
        starts_at = cursor
        cursor += clip.duration
        timeline.append(
            {
                "id": clip.id,
                "title": clip.title,
                "source": clip.source,
                "source_start": clip.start,
                "source_end": clip.end,
                "startsAt": round(starts_at, 3),
                "endsAt": round(cursor, 3),
                "caption": clip.caption,
                "narration": clip.narration or clip.caption,
            }
        )
    (build_dir / "segments.txt").write_text(
        "".join(f"file '{path.as_posix()}'\n" for path in segment_paths),
        encoding="utf-8",
    )
    return timeline


def render_clip(source: Path, output: Path, clip: Clip) -> None:
    video_filters = ["scale=1280:720", "fps=25", "format=yuv420p"]
    if clip.hide_sidebar:
        video_filters.append(SIDEBAR_HISTORY_MASK_FILTER)
        video_filters.append(SIDEBAR_HISTORY_LOWER_EDGE_MASK_FILTER)
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-ss",
            f"{clip.start:.3f}",
            "-to",
            f"{clip.end:.3f}",
            "-i",
            str(source),
            "-an",
            "-vf",
            ",".join(video_filters),
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "23",
            "-movflags",
            "+faststart",
            str(output),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def concat_clips(build_dir: Path, output: Path) -> None:
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(build_dir / "segments.txt"),
            "-c",
            "copy",
            "-movflags",
            "+faststart",
            str(output),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def write_srt(timeline: list[dict[str, Any]], path: Path) -> None:
    blocks = []
    for index, scene in enumerate(timeline, start=1):
        blocks.append(
            "\n".join(
                [
                    str(index),
                    f"{srt_time(scene['startsAt'])} --> {srt_time(scene['endsAt'])}",
                    wrap_caption(str(scene["caption"])),
                ]
            )
        )
    path.write_text("\n\n".join(blocks) + "\n", encoding="utf-8")


def write_storyboard(timeline: list[dict[str, Any]], path: Path) -> None:
    lines = ["# 客户版实操演示视频分镜", ""]
    for index, scene in enumerate(timeline, start=1):
        lines.extend(
            [
                f"## {index:02d}. {scene['title']}",
                "",
                f"Time: `{hms(scene['startsAt'])}` - `{hms(scene['endsAt'])}`",
                "",
                f"Source: `{scene['source']}` `{hms(scene['source_start'])}` - `{hms(scene['source_end'])}`",
                "",
                str(scene["caption"]),
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")


def write_voiceover(timeline: list[dict[str, Any]], path: Path) -> None:
    lines = [
        "# 客户版实操演示视频旁白稿",
        "",
        "这份稿子用于人工讲解或导入剪映生成中文配音。语速建议偏慢，遇到画面等待时可以停顿。",
        "",
    ]
    for index, scene in enumerate(timeline, start=1):
        lines.extend(
            [
                f"## 第{index}段：{scene['title']}",
                "",
                str(scene["narration"]),
                "",
            ]
        )
    lines.extend(
        [
            "## 收尾",
            "",
            "这套流程的重点不是多一个页面，而是让对话、资料、记忆、任务和创作保持在同一个工作流里。",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def write_manifest(
    basename: str,
    timeline: list[dict[str, Any]],
    mp4: Path,
    srt: Path,
    storyboard: Path,
    voiceover: Path,
    manifest: Path,
) -> None:
    payload = {
        "schema": "pska.hermes_extension_playwright_recording.v1",
        "demo_case": {
            "id": "customer_walkthrough",
            "title": "客户版实操讲解",
            "source_root": "",
        },
        "base_url": "http://127.0.0.1:8787",
        "mp4": str(mp4.relative_to(ROOT)),
        "subtitles": str(srt.relative_to(ROOT)),
        "storyboard": str(storyboard.relative_to(ROOT)),
        "voiceover": str(voiceover.relative_to(ROOT)),
        "timeline": timeline,
        "no_tts": True,
        "entrypoint": "Hermes WebUI extension",
        "output_basename": basename,
        "composition": {
            "source_recordings": sorted({clip.source for clip in CLIPS}),
            "audio": "none",
            "purpose": "customer_facing_operational_walkthrough",
            "visual_cleanup": {
                "sidebar_history_masked": True,
                "mask_filters": [
                    SIDEBAR_HISTORY_MASK_FILTER,
                    SIDEBAR_HISTORY_LOWER_EDGE_MASK_FILTER,
                ],
            },
        },
    }
    manifest.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def ffprobe_duration(path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(path)],
        check=True,
        text=True,
        capture_output=True,
    )
    return float(result.stdout.strip())


def srt_time(seconds: float) -> str:
    millis = int(round(seconds * 1000))
    hours, remainder = divmod(millis, 3_600_000)
    minutes, remainder = divmod(remainder, 60_000)
    secs, millis = divmod(remainder, 1_000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"


def hms(seconds: float) -> str:
    millis = int(round(seconds * 1000))
    hours, remainder = divmod(millis, 3_600_000)
    minutes, remainder = divmod(remainder, 60_000)
    secs, millis = divmod(remainder, 1_000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d}.{millis:03d}"


def wrap_caption(text: str, width: int = 24) -> str:
    lines = []
    current = ""
    for char in text:
        current += char
        if len(current) >= width:
            lines.append(current)
            current = ""
    if current:
        lines.append(current)
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
